#!/usr/bin/env python
# -*- python -*-

import re
import pymongo

RE_VAR = re.compile("%{([a-zA-Z0-9._-]+)}")
MINITREE_SERVER = "http://localhost:8000"
MONGO_SERVER = "localhost:27017"
DEBUG = True

def info(message): print message
def warn(message): print message

def tree_send(node_path, data="", method="", mode="r"):
    import urllib2
    from cjson import decode as json_decode
    modemap = dict(c="PUT", r="GET", u="POST", d="DELETE")
    url = MINITREE_SERVER.rstrip("/") + "/node/" + node_path.replace(".", "/")
    if method:
        url = url + "?method=" + method
    opener = urllib2.build_opener(urllib2.HTTPHandler)
    request = urllib2.Request(url, data)
    request.get_method = lambda: modemap[mode]
    return json_decode(opener.open(request).read())

def _expand_var(v, node):
    if v[0] in node:
        if node[v[0]][0] == '@':
            node = tree_send(node[v[0]][1:])
            return _expand_var(v[1:], node)
        else:
            return node[v[0]]
    else:
        warn("`%s' not exists in node `%s'" % (v, repr(node)))

def expand_var(pair, node):

    def _match(v, node):
        node_path = v.group(1).split(".")
        return _expand_var(node_path, node)

    key, value = pair
    expaneded = RE_VAR.sub(lambda x: _match(x, node), value)
    return (key, expaneded)

def connect_cache_server(server):
    hostname, port = server.split(":", 2)
    return pymongo.Connection(hostname, int(port))

def build_cache(manifest_path):
    cache_path = "cache.manifest." + manifest_path.lstrip(".")
    manifest = tree_send(cache_path)
    target = manifest["__target__"]
    cache_conn = connect_cache_server(MONGO_SERVER)
    fields = filter(lambda x: not(x.startswith("__")
                                  and x.endswith("__")), manifest.keys())
    nodes = tree_send(target, method="children")
    for node_name in nodes:
        info("rebuilding `%s' ..." % node_name)
        node = tree_send(node_name)
        cache = dict(map(lambda x: expand_var(x, node),
                         map(lambda x: (x, manifest[x]), fields)))
        write_cache(cache_conn, node_name, cache)

def write_cache(cache_conn, node_path, cache):
    splits = node_path.split(".")
    assert(len(splits) > 2)
    dbname = "_".join(splits[0:2])
    db = cache_conn[dbname]
    coll = db[splits[2]]
    cache["__node_path__"] = node_path
    coll.update({"__node_path__": node_path}, {"$set": cache}, True)

if __name__ == '__main__':
    import sys
    build_cache(sys.argv[1])

