#!/usr/bin/env python
# -*- python -*-
from yaml import safe_load as yaml_load, safe_dump as yaml_dump
from cjson import decode as json_decode, encode as json_encode
from tempfile import mkstemp
from urllib2 import urlopen
import os

node_server = "http://localhost:8000"


def _edit(resource_path, tmpfile):

    editor = os.environ["EDITOR"]

    json = urlopen(resource_path).read()
    yaml = yaml_dump(json_decode(json), default_flow_style=False)

    with open(tmpfile, "w") as f:
        f.write(yaml)

    os.system("%s '%s'" % (editor, tmpfile))

    with open(tmpfile, "r") as f:
        modifed_yaml = yaml_load(f.read())
        modifed_json = json_encode(modifed_yaml)
        ret = urlopen(url, modifed_json)
        ret_code = ret.getcode()
        ret_json = json_decode(ret.read())
        if ret_code == 200:
            print ret_json["success"]
        else:
            print ret_json["error"]

def node2resource(node_path):
    return "/node/" + node_path.replace(".", "/").rstrip("/")

def edit(node_path):
    resource_path = node_server.rstrip("/") + node2resource(node_path)
    fd, tmpfile = mkstemp(prefix="vitree-")
    os.close(fd)
    success = False
    while not success:
        try:
            _edit(resource_path, tmpfile)
        except:
            raise
        finally:
            os.unlink(tmpfile)

if __name__ == '__main__':
    import sys
    edit(sys.argv[1])

